services:
  app:
    image: expense-tracker:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
