services:
  app:
    image: expense-tracker:latest
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: expense-db:latest
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
