name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build APP container
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile.app
        push: false
        load: true
        tags: expense-tracker:latest
    
    - name: Build database container
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile.db
        push: false
        load: true
        tags: expense-db:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./tests/requirements.txt
    
    - name: Create network
      run: docker network create expense-tracker-network || true
      
    - name: Start services for testing
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: docker-compose.yaml
        services: |
          app
          db
        
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings tests/test_app.py
